CREATE TABLE USUARIO1
(
    NOMBRE VARCHAR2(15),
    APELLIDOS VARCHAR2(15),
    EDAD NUMBER,
    DIRECCION VARCHAR2(30),
    Nº DE HERMANOS NUMBER,
    CORREO ELECTRONICO DEL ALUMNO VARCHAR2(15)

);

CREATE TABLE AULA2
(
    NOMBRE_AULA VARCHAR2(15),
    CAPACIDAD NUMBER,
    PLANTA NUMBER,
    dESCRIPCION VARCHAR2(50)
);